//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITToolbelt.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITToolbelt.Shared.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı boş bırakılamaz.
        /// </summary>
        public static string _001 {
            get {
                return ResourceManager.GetString("001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı boş bırakılamaz.
        /// </summary>
        public static string _002 {
            get {
                return ResourceManager.GetString("002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail boş bırakılamaz.
        /// </summary>
        public static string _003 {
            get {
                return ResourceManager.GetString("003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri tabanı bağlantısı hatası.
        /// </summary>
        public static string _004 {
            get {
                return ResourceManager.GetString("004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string _005 {
            get {
                return ResourceManager.GetString("005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASİF.
        /// </summary>
        public static string _006 {
            get {
                return ResourceManager.GetString("006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKTİF.
        /// </summary>
        public static string _007 {
            get {
                return ResourceManager.GetString("007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarların aktifleşmesi için uygulamanın yeniden başlatılması gerekmektedir. Şimdi yeniden başlatmak ister misiniz?.
        /// </summary>
        public static string _008 {
            get {
                return ResourceManager.GetString("008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string _009 {
            get {
                return ResourceManager.GetString("009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} silinecek, onaylıyor musunuz? Bu işlem geri alınamaz?.
        /// </summary>
        public static string _010 {
            get {
                return ResourceManager.GetString("010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün indeksler pasif yapıldı..
        /// </summary>
        public static string _011 {
            get {
                return ResourceManager.GetString("011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilendirme.
        /// </summary>
        public static string _012 {
            get {
                return ResourceManager.GetString("012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bazı indekslerin pasif edilmesi sırasında hata oluştu..
        /// </summary>
        public static string _013 {
            get {
                return ResourceManager.GetString("013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string _014 {
            get {
                return ResourceManager.GetString("014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı ekleme.
        /// </summary>
        public static string _015 {
            get {
                return ResourceManager.GetString("015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to başarılı.
        /// </summary>
        public static string _016 {
            get {
                return ResourceManager.GetString("016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to başarısız.
        /// </summary>
        public static string _017 {
            get {
                return ResourceManager.GetString("017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string _018 {
            get {
                return ResourceManager.GetString("018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string _019 {
            get {
                return ResourceManager.GetString("019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARTAN.
        /// </summary>
        public static string _020 {
            get {
                return ResourceManager.GetString("020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZALAN.
        /// </summary>
        public static string _021 {
            get {
                return ResourceManager.GetString("021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı alanı en fazla 50 karakter olabilir..
        /// </summary>
        public static string _022 {
            get {
                return ResourceManager.GetString("022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı alanı en fazla 50 karakter olabilir..
        /// </summary>
        public static string _023 {
            get {
                return ResourceManager.GetString("023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail alanı en fazla 100 karakter olabilir..
        /// </summary>
        public static string _024 {
            get {
                return ResourceManager.GetString("024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adı daha önce kullanılmış..
        /// </summary>
        public static string _025 {
            get {
                return ResourceManager.GetString("025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarılı..
        /// </summary>
        public static string _026 {
            get {
                return ResourceManager.GetString("026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı boş bırakılamaz.
        /// </summary>
        public static string _027 {
            get {
                return ResourceManager.GetString("027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı alanı en fazla 50 karakter olabilir..
        /// </summary>
        public static string _028 {
            get {
                return ResourceManager.GetString("028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarısız..
        /// </summary>
        public static string _029 {
            get {
                return ResourceManager.GetString("029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama alanı en fazla 500 karakter olabilir.
        /// </summary>
        public static string _030 {
            get {
                return ResourceManager.GetString("030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu grup adı daha önce kaydedilmiş.
        /// </summary>
        public static string _031 {
            get {
                return ResourceManager.GetString("031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu bilgisayar adı daha önce kaydedilmiş.
        /// </summary>
        public static string _032 {
            get {
                return ResourceManager.GetString("032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bilgisayarından {1} isimli kullanıcı kaldırılacak. Bu işlem geri alınamaz. Onaylıyor musunuz?.
        /// </summary>
        public static string _033 {
            get {
                return ResourceManager.GetString("033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama adı boş bırakılamaz.
        /// </summary>
        public static string _034 {
            get {
                return ResourceManager.GetString("034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama adı en fazla 100 karakter olabilir.
        /// </summary>
        public static string _035 {
            get {
                return ResourceManager.GetString("035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama yayınlayıcısı boş bırakılamaz.
        /// </summary>
        public static string _036 {
            get {
                return ResourceManager.GetString("036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama versiyonu boş bırakılamaz.
        /// </summary>
        public static string _037 {
            get {
                return ResourceManager.GetString("037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama mimarisi boş bırakılamaz.
        /// </summary>
        public static string _038 {
            get {
                return ResourceManager.GetString("038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama yayıncısı en fazla 100 karakter olabilir.
        /// </summary>
        public static string _039 {
            get {
                return ResourceManager.GetString("039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama versiyonu en fazla 20 karakter olabilir.
        /// </summary>
        public static string _040 {
            get {
                return ResourceManager.GetString("040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama mimarisi &quot;32 Bit&quot; veya &quot;64 Bit&quot; olabilir.
        /// </summary>
        public static string _041 {
            get {
                return ResourceManager.GetString("041", resourceCulture);
            }
        }
    }
}
